name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/nathan-thomas-mael:${{ github.run_id }}
    steps:
    - uses: actions/checkout@v4

    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_SECRET_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

    - name: Test the Docker image build
      run: docker build --target test . --tag nathan-thomas-mael:test

    - name: Notify on build failure
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_CHANNEL: builds
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Build of Docker image failed for run ID ${{ github.run_id }}.'
        SLACK_TITLE: 'Build Failed :x:'
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify on build success
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_CHANNEL: builds
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Build of Docker image succeeded for run ID ${{ github.run_id }}.'
        SLACK_TITLE: 'Build Succeeded :tada:'
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    needs: build-test
    if: contains(github.event.head_commit.message, '#deploy')
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/nathan-thomas-mael:${{ github.run_id }}
    steps:
    - uses: actions/checkout@v4

    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_SECRET_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

    - name: Build the Docker image
      run: docker build --target build . --tag $IMAGE_TAG

    - name: Push the Docker Image
      run: docker push $IMAGE_TAG

    - name: Notify on deployment failure
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_CHANNEL: builds
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Deployment of Docker image failed for run ID ${{ github.run_id }}.'
        SLACK_TITLE: 'Deployment Failed :x:'
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify on deployment success
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_CHANNEL: builds
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Deployment of Docker image succeeded for run ID ${{ github.run_id }}.'
        SLACK_TITLE: 'Deployment Succeeded :tada:'
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}